/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminWaitlistRouteImport } from './routes/admin.waitlist'
import { Route as AdminStaffRouteImport } from './routes/admin.staff'
import { Route as AdminCompaniesIndexRouteImport } from './routes/admin.companies.index'
import { Route as AdminCompaniesIdRouteImport } from './routes/admin.companies.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWaitlistRoute = AdminWaitlistRouteImport.update({
  id: '/admin/waitlist',
  path: '/admin/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/admin/staff',
  path: '/admin/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCompaniesIndexRoute = AdminCompaniesIndexRouteImport.update({
  id: '/admin/companies/',
  path: '/admin/companies/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCompaniesIdRoute = AdminCompaniesIdRouteImport.update({
  id: '/admin/companies/$id',
  path: '/admin/companies/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/waitlist': typeof AdminWaitlistRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/companies/$id': typeof AdminCompaniesIdRoute
  '/admin/companies/': typeof AdminCompaniesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/waitlist': typeof AdminWaitlistRoute
  '/admin': typeof AdminIndexRoute
  '/admin/companies/$id': typeof AdminCompaniesIdRoute
  '/admin/companies': typeof AdminCompaniesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/waitlist': typeof AdminWaitlistRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/companies/$id': typeof AdminCompaniesIdRoute
  '/admin/companies/': typeof AdminCompaniesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/staff'
    | '/admin/waitlist'
    | '/admin/'
    | '/admin/companies/$id'
    | '/admin/companies/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/staff'
    | '/admin/waitlist'
    | '/admin'
    | '/admin/companies/$id'
    | '/admin/companies'
  id:
    | '__root__'
    | '/'
    | '/admin/staff'
    | '/admin/waitlist'
    | '/admin/'
    | '/admin/companies/$id'
    | '/admin/companies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminWaitlistRoute: typeof AdminWaitlistRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCompaniesIdRoute: typeof AdminCompaniesIdRoute
  AdminCompaniesIndexRoute: typeof AdminCompaniesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/waitlist': {
      id: '/admin/waitlist'
      path: '/admin/waitlist'
      fullPath: '/admin/waitlist'
      preLoaderRoute: typeof AdminWaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/admin/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/companies/': {
      id: '/admin/companies/'
      path: '/admin/companies'
      fullPath: '/admin/companies/'
      preLoaderRoute: typeof AdminCompaniesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/companies/$id': {
      id: '/admin/companies/$id'
      path: '/admin/companies/$id'
      fullPath: '/admin/companies/$id'
      preLoaderRoute: typeof AdminCompaniesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminWaitlistRoute: AdminWaitlistRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCompaniesIdRoute: AdminCompaniesIdRoute,
  AdminCompaniesIndexRoute: AdminCompaniesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
