/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaitlistRouteImport } from './routes/waitlist'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StockIndexRouteImport } from './routes/stock.index'
import { Route as ReceiptsIndexRouteImport } from './routes/receipts.index'
import { Route as DiesIndexRouteImport } from './routes/dies.index'
import { Route as CustomersIndexRouteImport } from './routes/customers.index'
import { Route as BundlesIndexRouteImport } from './routes/bundles.index'
import { Route as SettingsMembersRouteImport } from './routes/settings.members'
import { Route as ReceiptsNewRouteImport } from './routes/receipts.new'
import { Route as ReceiptsIdRouteImport } from './routes/receipts.$id'
import { Route as PlatformWaitlistRouteImport } from './routes/platform.waitlist'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as DiesIdRouteImport } from './routes/dies.$id'
import { Route as CustomersIdRouteImport } from './routes/customers.$id'
import { Route as BundlesIdRouteImport } from './routes/bundles.$id'

const WaitlistRoute = WaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StockIndexRoute = StockIndexRouteImport.update({
  id: '/stock/',
  path: '/stock/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsIndexRoute = ReceiptsIndexRouteImport.update({
  id: '/receipts/',
  path: '/receipts/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiesIndexRoute = DiesIndexRouteImport.update({
  id: '/dies/',
  path: '/dies/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const BundlesIndexRoute = BundlesIndexRouteImport.update({
  id: '/bundles/',
  path: '/bundles/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsMembersRoute = SettingsMembersRouteImport.update({
  id: '/settings/members',
  path: '/settings/members',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsNewRoute = ReceiptsNewRouteImport.update({
  id: '/receipts/new',
  path: '/receipts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsIdRoute = ReceiptsIdRouteImport.update({
  id: '/receipts/$id',
  path: '/receipts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformWaitlistRoute = PlatformWaitlistRouteImport.update({
  id: '/platform/waitlist',
  path: '/platform/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DiesIdRoute = DiesIdRouteImport.update({
  id: '/dies/$id',
  path: '/dies/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIdRoute = CustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BundlesIdRoute = BundlesIdRouteImport.update({
  id: '/bundles/$id',
  path: '/bundles/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/waitlist': typeof WaitlistRoute
  '/bundles/$id': typeof BundlesIdRoute
  '/customers/$id': typeof CustomersIdRoute
  '/dies/$id': typeof DiesIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/platform/waitlist': typeof PlatformWaitlistRoute
  '/receipts/$id': typeof ReceiptsIdRoute
  '/receipts/new': typeof ReceiptsNewRoute
  '/settings/members': typeof SettingsMembersRoute
  '/bundles/': typeof BundlesIndexRoute
  '/customers/': typeof CustomersIndexRoute
  '/dies/': typeof DiesIndexRoute
  '/receipts/': typeof ReceiptsIndexRoute
  '/stock/': typeof StockIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/waitlist': typeof WaitlistRoute
  '/bundles/$id': typeof BundlesIdRoute
  '/customers/$id': typeof CustomersIdRoute
  '/dies/$id': typeof DiesIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/platform/waitlist': typeof PlatformWaitlistRoute
  '/receipts/$id': typeof ReceiptsIdRoute
  '/receipts/new': typeof ReceiptsNewRoute
  '/settings/members': typeof SettingsMembersRoute
  '/bundles': typeof BundlesIndexRoute
  '/customers': typeof CustomersIndexRoute
  '/dies': typeof DiesIndexRoute
  '/receipts': typeof ReceiptsIndexRoute
  '/stock': typeof StockIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/waitlist': typeof WaitlistRoute
  '/bundles/$id': typeof BundlesIdRoute
  '/customers/$id': typeof CustomersIdRoute
  '/dies/$id': typeof DiesIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/platform/waitlist': typeof PlatformWaitlistRoute
  '/receipts/$id': typeof ReceiptsIdRoute
  '/receipts/new': typeof ReceiptsNewRoute
  '/settings/members': typeof SettingsMembersRoute
  '/bundles/': typeof BundlesIndexRoute
  '/customers/': typeof CustomersIndexRoute
  '/dies/': typeof DiesIndexRoute
  '/receipts/': typeof ReceiptsIndexRoute
  '/stock/': typeof StockIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/waitlist'
    | '/bundles/$id'
    | '/customers/$id'
    | '/dies/$id'
    | '/invite/$token'
    | '/platform/waitlist'
    | '/receipts/$id'
    | '/receipts/new'
    | '/settings/members'
    | '/bundles/'
    | '/customers/'
    | '/dies/'
    | '/receipts/'
    | '/stock/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/waitlist'
    | '/bundles/$id'
    | '/customers/$id'
    | '/dies/$id'
    | '/invite/$token'
    | '/platform/waitlist'
    | '/receipts/$id'
    | '/receipts/new'
    | '/settings/members'
    | '/bundles'
    | '/customers'
    | '/dies'
    | '/receipts'
    | '/stock'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/waitlist'
    | '/bundles/$id'
    | '/customers/$id'
    | '/dies/$id'
    | '/invite/$token'
    | '/platform/waitlist'
    | '/receipts/$id'
    | '/receipts/new'
    | '/settings/members'
    | '/bundles/'
    | '/customers/'
    | '/dies/'
    | '/receipts/'
    | '/stock/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  WaitlistRoute: typeof WaitlistRoute
  BundlesIdRoute: typeof BundlesIdRoute
  CustomersIdRoute: typeof CustomersIdRoute
  DiesIdRoute: typeof DiesIdRoute
  InviteTokenRoute: typeof InviteTokenRoute
  PlatformWaitlistRoute: typeof PlatformWaitlistRoute
  ReceiptsIdRoute: typeof ReceiptsIdRoute
  ReceiptsNewRoute: typeof ReceiptsNewRoute
  SettingsMembersRoute: typeof SettingsMembersRoute
  BundlesIndexRoute: typeof BundlesIndexRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
  DiesIndexRoute: typeof DiesIndexRoute
  ReceiptsIndexRoute: typeof ReceiptsIndexRoute
  StockIndexRoute: typeof StockIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/waitlist': {
      id: '/waitlist'
      path: '/waitlist'
      fullPath: '/waitlist'
      preLoaderRoute: typeof WaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock/': {
      id: '/stock/'
      path: '/stock'
      fullPath: '/stock/'
      preLoaderRoute: typeof StockIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipts/': {
      id: '/receipts/'
      path: '/receipts'
      fullPath: '/receipts/'
      preLoaderRoute: typeof ReceiptsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
      parentRoute: typeof rootRouteImport
    }
    '/dies/': {
      id: '/dies/'
      path: '/dies'
      fullPath: '/dies/'
      preLoaderRoute: typeof DiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bundles/': {
      id: '/bundles/'
      path: '/bundles'
      fullPath: '/bundles/'
      preLoaderRoute: typeof BundlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/members': {
      id: '/settings/members'
      path: '/settings/members'
      fullPath: '/settings/members'
      preLoaderRoute: typeof SettingsMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipts/new': {
      id: '/receipts/new'
      path: '/receipts/new'
      fullPath: '/receipts/new'
      preLoaderRoute: typeof ReceiptsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipts/$id': {
      id: '/receipts/$id'
      path: '/receipts/$id'
      fullPath: '/receipts/$id'
      preLoaderRoute: typeof ReceiptsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/waitlist': {
      id: '/platform/waitlist'
      path: '/platform/waitlist'
      fullPath: '/platform/waitlist'
      preLoaderRoute: typeof PlatformWaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
      parentRoute: typeof rootRouteImport
    }
      parentRoute: typeof rootRouteImport
    }
    '/dies/$id': {
      id: '/dies/$id'
      path: '/dies/$id'
      fullPath: '/dies/$id'
      preLoaderRoute: typeof DiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$id': {
      id: '/customers/$id'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof CustomersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bundles/$id': {
      id: '/bundles/$id'
      path: '/bundles/$id'
      fullPath: '/bundles/$id'
      preLoaderRoute: typeof BundlesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  WaitlistRoute: WaitlistRoute,
  BundlesIdRoute: BundlesIdRoute,
  CustomersIdRoute: CustomersIdRoute,
  DiesIdRoute: DiesIdRoute,
  InviteTokenRoute: InviteTokenRoute,
  PlatformWaitlistRoute: PlatformWaitlistRoute,
  ReceiptsIdRoute: ReceiptsIdRoute,
  ReceiptsNewRoute: ReceiptsNewRoute,
  SettingsMembersRoute: SettingsMembersRoute,
  BundlesIndexRoute: BundlesIndexRoute,
  CustomersIndexRoute: CustomersIndexRoute,
  DiesIndexRoute: DiesIndexRoute,
  ReceiptsIndexRoute: ReceiptsIndexRoute,
  StockIndexRoute: StockIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
